name: Set (multiline) text output
description: A composite action to set the job output while maintaining the format e.g. markdown format and multi-line strings.
author: 'Manuel Rauber <info@boundfoxstudios.com>'
branding:
  icon: align-left
  color: orange

inputs:
  text:
    description: Text content to be set as job output
    required: true

outputs:
  value:
    description: outputs text and maintains the text format.
    value: ${{ steps.set.outputs.value }}

runs:
  using: composite
  steps:
    - id: set
      shell: bash
      env:
        text: ${{ inputs.text }}
      run: |
        text="${text//'%'/'%25'}"
        text="${text//$'\n'/'%0A'}"
        text="${text//$'\r'/'%0D'}"
        echo "value=$text" >> $GITHUB_OUTPUT
