name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      content: |
        # test basic

        test content

    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: test1
        with:
          markdown: $content
      - if: ${{ env.content }} != ${{ steps.test1.outputs.value }}
        run: |
          echo "${{ env.content }}\n"
          echo "${{ steps.test1.outputs.value }}\n"
