name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      content: |
        # test heading

        Lorem ipsum dolor sit amet, consectetur adipisicing elit,
        sed do eiusmod tempor incididunt ut labore et dolore magna
        aliqua. Ut enim ad minim veniam, quis nostrud exercitation
        ullamco laboris nisi ut aliquip ex ea commodo consequat.
        Duis aute irure dolor in reprehenderit in voluptate velit
        esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
        occaecat cupidatat non proident, sunt in culpa qui officia
        deserunt mollit anim id est laborum.

    steps:
      - uses: actions/checkout@v2
      - id: expected
        env:
          text: $content
        run: |
          text="${text//'%'/'%25'}"
          text="${text//$'\n'/'%0A'}"
          text="${text//$'\r'/'%0D'}"
          echo "::set-output name=content::$text"

      - name: "test simple"
        uses: ./
        id: test1
        with:
          text: $content
      - name: "test simple failed"
        if: ${{ steps.expected.outputs.content != steps.test1.outputs.value }}
        run: |
          echo "expected:"
          echo "${{ steps.expected.outputs.content }}"
          echo "got:"
          echo "${{ toJSON(steps.test1.outputs) }}"
          exit 1

  test-usage:
    runs-on: ubuntu-latest
    outputs:
      content: ${{ steps.content.outputs.value }}
    steps:
      - name: "test simple"
        uses: howijd/actions-set-text-output@main
        id: content
        with:
          text: |
            # Set text output

            A simple composite actions to set the job output while maintaining the text format e.g. markdown format.

  test-result:
    runs-on: ubuntu-latest
    needs: test-usage
    if: always()
    steps:
      - if: startsWith(needs.test-usage.outputs.content, '# Set text output')
        run: exit 0
      - if: ${{ !startsWith(needs.test-usage.outputs.content, '# Set text output') }}
        run: exit 1

  v1-test:
    runs-on: ubuntu-latest
    outputs:
      content: ${{ steps.content.outputs.value }}
    steps:
      - name: "test simple"
        uses: howijd/actions-set-text-output@v1
        id: content
        with:
          text: |
            # Set text output

            A simple composite actions to set the job output while maintaining the text format e.g. markdown format.

  v1-result:
    runs-on: ubuntu-latest
    needs: test-usage
    if: always()
    steps:
      - if: startsWith(needs.test-usage.outputs.content, '# Set text output')
        run: exit 0
      - if: ${{ !startsWith(needs.test-usage.outputs.content, '# Set text output') }}
        run: exit 1