name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      content: |
        # test heading

        Lorem ipsum dolor sit amet, consectetur adipisicing elit,
        sed do eiusmod tempor incididunt ut labore et dolore magna
        aliqua. Ut enim ad minim veniam, quis nostrud exercitation
        ullamco laboris nisi ut aliquip ex ea commodo consequat.
        Duis aute irure dolor in reprehenderit in voluptate velit
        esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
        occaecat cupidatat non proident, sunt in culpa qui officia
        deserunt mollit anim id est laborum.

    steps:
      - uses: actions/checkout@v2
      - id: expected
        env:
          text: $content
        run: |
          text="${text//'%'/'%25'}"
          text="${text//$'\n'/'%0A'}"
          text="${text//$'\r'/'%0D'}"
          echo "::set-output name=text::$markdown"
      - uses: ./
        id: test1
        with:
          text: $content
      - name: "test simple failed"
        if: ${{ steps.expected.outputs.text != steps.test1.outputs.value }}
        run: |
          echo "expected: \n${{ steps.expected.outputs.content }}\n"
          echo "got: \n${{ steps.test1.outputs.value }}\n"
          exit 1
